#!/bin/bash

PROJECT=$1
HERE=`pwd`
HOSTNAME=snowball
IP_BOARD=192.168.77.42
MAC_ADDRESS=02:00:00:42:00:01

ROOTFS_CONFIG=$HERE/system/$PROJECT/rootfs_config/
CONFIG_MULTISTRAP=$ROOTFS_CONFIG/config/${HOSTNAME}_multistrap_configuration

REPO_SOURCE="http://ftp.fr.debian.org/debian/"
REPO_PACKAGES="ntpdate udev lrzsz netcat telnetd net-tools openssh-server iputils-ping apt nano isc-dhcp-client build-essential module-init-tools wireless-tools git"

SETUP_SCRIPT=$ROOTFS_CONFIG/scripts/${HOSTNAME}_setup_script.sh
CONFIG_SCRIPT=$ROOTFS_CONFIG/scripts/${HOSTNAME}_config_script.sh

##########################################################
# Create multistrap's configuration file

echo "[General]" > $CONFIG_MULTISTRAP
{
    echo "arch=armel"
    echo "directory=./rootfs"
    echo "cleanup=true"
    echo "#same as --no-auth option if set to true"
    echo "noauth=true"
    echo "unpack=true"
    echo
    echo "#Configuration scripts to use"
    echo "setupscript=$SETUP_SCRIPT"
    echo "configscript=$CONFIG_SCRIPT"

    echo
    echo "#Filesystem will be placed in"
    echo "tarballname=./boot/rootfs-armel-snowball.tar"
    echo
    echo "aptsources=squeeze"
    echo "bootstrap=squeeze"
    echo
    echo "[squeeze]"
    echo "packages=$REPO_PACKAGES"
    echo "source=$REPO_SOURCE"
    echo "suite=squeeze"
    echo "omitdebsrc=true"
} | cat >> $CONFIG_MULTISTRAP

##########################################################
# Create SETUP script

cat << EOF > $SETUP_SCRIPT
#!/bin/sh

echo "Setting hostname"
echo "$HOSTNAME" > $ROOTFS_CONFIG/etc/hostname

echo "Setting up root user (user=root password=root)"
echo "root:Npge08pfz4wuk:0:0:root:/root:/bin/bash" > $ROOTFS_CONFIG/etc/passwd
echo "root:Npge08pfz4wuk:0:" > $ROOTFS_CONFIG/etc/group

echo "Setting up fstab"
echo "proc /proc proc defaults 0 0" >> $ROOTFS_CONFIG/etc/fstab
echo "sysfs /sys sysfs defaults 0 0" >> $ROOTFS_CONFIG/etc/fstab

echo "Copying kernel modules"
if [ ! -d $ROOTFS_CONFIG/lib/modules ]; then mkdir $ROOTFS_CONFIG/lib/modules; fi
sudo cp -r ./modules/lib/modules/* $ROOTFS_CONFIG/lib/modules/

echo "Setting a mac address (fixing random mac issue)"
{
    echo "auto lo";
    echo "iface lo inet loopback";
    echo "";
    echo "auto eth0";
    echo "iface eth0 inet static";
    echo "address $IP_BOARD";
    echo "netmask 255.255.255.0";
    echo "hwaddress ether $MAC_ADDRESS";
} | cat > $ROOTFS_CONFIG/etc/network/interfaces

echo "Setting up /dev"
sudo mknod $ROOTFS_CONFIG/dev/console c 5 1
sudo mknod $ROOTFS_CONFIG/dev/null c 1 3
sudo mknod $ROOTFS_CONFIG/dev/ttyS0 c 4 64
sudo mknod $ROOTFS_CONFIG/dev/ttyS1 c 4 65
sudo mknod $ROOTFS_CONFIG/dev/ttyS2 c 4 66

EOF

chmod a+x $SETUP_SCRIPT


##########################################################
# Create CONFIG script#

cat << EOF > $CONFIG_SCRIPT
#!/bin/sh

echo "Mounting /proc"
mount -n /proc
mount -n /sys
dpkg --configure -a
echo ttyS0 >> etc/securetty
printf "T0:123:respawn:/sbin/getty 115200 ttyS0\n" >> etc/inittab
echo "Set a new root password"
passwd
chage -d 150 root
echo "You need to reboot your system"
EOF
chmod a+x $CONFIG_SCRIPT

